Repository react-native-camera/react-native-camera, pull requests merged in 2019-06, with the labels that each got.

#2293 Add docusaurus
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  docs/API.md
  docs/Contributing.md
  docs/GradleUpgradeGuide.md
  docs/QA.md
  docs/RNCamera.md
  docs/Recipes.md
  docs/expo_usage.md
  docs/installation.md
  docs/migration.md
  docs/migrationV2.md
  docs/react-navigation.md
  docs/tests.md
  website/README.md
  website/core/Footer.js
  website/i18n/en.json
  website/package.json
  website/pages/en/help.js
  website/pages/en/index.js
  website/pages/en/users.js
  website/sidebars.json
  website/siteConfig.js
  website/static/css/code-block-buttons.css
  website/static/css/custom.css
  website/static/img/community.png
  website/static/img/favicon.ico
  website/static/img/oss_logo.png
  website/static/img/undraw_code_review.svg
  website/static/img/undraw_monitor.svg
  website/static/img/undraw_note_list.svg
  website/static/img/undraw_online.svg
  website/static/img/undraw_open_source.svg
  website/static/img/undraw_operating_system.svg
  website/static/img/undraw_react.svg
  website/static/img/undraw_tweetstorm.svg
  website/static/img/undraw_youtube_tutorial.svg
  website/static/js/code-blocks-buttons.js
  website/yarn.lock
Labels: Documentation, Enhancement

#2068 upgrading to sdk 28 and androidx
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/src/general/java/org/reactnative/facedetector/tasks/FileFaceDetectionAsyncTask.java
  android/src/main/java/com/google/android/cameraview/AspectRatio.java
  android/src/main/java/com/google/android/cameraview/Camera1.java
  android/src/main/java/com/google/android/cameraview/Camera2.java
  android/src/main/java/com/google/android/cameraview/CameraView.java
  android/src/main/java/com/google/android/cameraview/Size.java
  android/src/main/java/com/google/android/cameraview/SizeMap.java
  android/src/main/java/com/google/android/cameraview/SurfaceViewPreview.java
  android/src/main/java/com/lwansbrough/RCTCamera/MutableImage.java
  android/src/main/java/com/lwansbrough/RCTCamera/RCTCameraViewManager.java
  android/src/main/java/org/reactnative/camera/CameraViewManager.java
  android/src/main/java/org/reactnative/camera/RNCameraView.java
  android/src/main/java/org/reactnative/camera/RNCameraViewHelper.java
  android/src/main/java/org/reactnative/camera/events/BarCodeReadEvent.java
  android/src/main/java/org/reactnative/camera/events/BarcodeDetectionErrorEvent.java
  android/src/main/java/org/reactnative/camera/events/BarcodesDetectedEvent.java
  android/src/main/java/org/reactnative/camera/events/CameraMountErrorEvent.java
  android/src/main/java/org/reactnative/camera/events/CameraReadyEvent.java
  android/src/main/java/org/reactnative/camera/events/FaceDetectionErrorEvent.java
  android/src/main/java/org/reactnative/camera/events/FacesDetectedEvent.java
  android/src/main/java/org/reactnative/camera/events/PictureSavedEvent.java
  android/src/main/java/org/reactnative/camera/events/PictureTakenEvent.java
  android/src/main/java/org/reactnative/camera/events/TextRecognizedEvent.java
  android/src/main/java/org/reactnative/camera/tasks/ResolveTakenPictureAsyncTask.java
  android/src/mlkit/java/org/reactnative/facedetector/tasks/FileFaceDetectionAsyncTask.java
  docs/AndroidXMigration.md
  examples/basic/android/app/build.gradle
  examples/basic/android/app/src/main/AndroidManifest.xml
  examples/basic/android/build.gradle
  examples/basic/android/gradle.properties
Labels: Android, Blocked

#2307 deploy docs based on master changes
  .circleci/config.yml
  website/core/Footer.js
  website/i18n/en.json
  website/siteConfig.js
Labels: Documentation, ci

#2313 Hotfix/deploy docs ci
  .circleci/config.yml
Labels: ci

#2339 Update RNCamera.m to fix video quality mismatch while recording multiple videos
  ios/RN/RNCamera.m
Labels: iOS

#2332 Chore - setting androidCameraPermissionOptions to examples
  examples/basic/App.js
  examples/mlkit/App.js
Labels: Android, Enhancement
